version: '3'
services:
  redis:
    image: redis
    volumes:
      - 'redis:/data'
  web:
    build: .
    ports:
      - "9292:9292"
    volumes:
      - .:/shorty
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    command: rackup -p 9292 -o 0.0.0.0
volumes:
  redis:
  web:
